name: property-fundamentals
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py36h68aa20f_2
  - arrow=1.0.3=py36ha15d459_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - binaryornot=0.4.4=py_1
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py36h68aa20f_1001
  - ca-certificates=2020.12.5=h5b45459_0
  - certifi=2020.12.5=py36ha15d459_1
  - cffi=1.14.5=py36he58ceb7_0
  - chardet=4.0.0=py36ha15d459_1
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cookiecutter=1.7.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py36hd0de82c_0
  - decorator=5.0.7=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.10.1=py36ha15d459_0
  - importlib_metadata=3.10.1=hd8ed1ab_0
  - ipykernel=5.5.3=py36hfacbf0b_0
  - ipython=7.16.1=py36h7b2dad6_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.2=py36ha15d459_1
  - jinja2=2.11.3=pyh44b312d_0
  - jinja2-time=0.2.0=py_2
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py36ha15d459_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - libiconv=1.16=he774522_0
  - libsodium=1.0.18=h8d14728_1
  - libxml2=2.9.10=hf5bbc77_3
  - libxslt=1.1.33=h65864e5_2
  - lxml=4.6.3=py36hf8cb5f9_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36h68aa20f_3
  - mistune=0.8.4=py36h68aa20f_1003
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py36ha15d459_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.3.0=py36ha15d459_0
  - openssl=1.1.1k=h8ffe710_0
  - packaging=20.9=pyh44b312d_0
  - pandoc=2.13=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - pickleshare=0.7.5=py_1003
  - pip=21.0.1=pyhd8ed1ab_0
  - poyo=0.5.0=py_0
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pykml=0.1.3=py36_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py36h68aa20f_2
  - pysocks=1.7.1=py36ha15d459_3
  - python=3.6.13=h39d44d4_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-slugify=4.0.1=pyh9f0ad1d_0
  - python_abi=3.6=1_cp36m
  - pywin32=300=py36h68aa20f_0
  - pywinpty=0.5.7=py36h9f0ad1d_1
  - pyzmq=22.0.3=py36h1d5d788_1
  - requests=2.25.1=pyhd3deb0d_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py36ha15d459_3
  - simplekml=1.3.5=pyh9f0ad1d_0
  - six=1.15.0=pyh9f0ad1d_0
  - terminado=0.9.4=py36ha15d459_0
  - testpath=0.4.4=py_0
  - text-unidecode=1.3=py_0
  - tornado=6.1=py36h68aa20f_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing_extensions=3.7.4.3=py_0
  - unidecode=1.2.0=pyhd8ed1ab_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - whichcraft=0.6.1=py_0
  - win_inet_pton=1.1.0=py36ha15d459_2
  - wincertstore=0.2=py36ha15d459_1006
  - winpty=0.4.3=4
  - zeromq=4.3.4=h0e60522_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
prefix: C:\Users\edgor\anaconda3\envs\property-fundamentals
